services:
  tg_postgres:
    image: postgres:16
    container_name: tg_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: telegram_demo
      POSTGRES_USER: telegram_user
      POSTGRES_PASSWORD: telegram_pass
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  tg_mysql:
    image: mysql:8.4
    container_name: tg_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: telegram_demo
      MYSQL_USER: telegram_user
      MYSQL_PASSWORD: telegram_pass
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  postgres_data:
  mysql_data:
